[package]
name = "markov_entropy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hi_sparse_bitset = "0.6.0"
rug = "1.24.1"
